// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ltTJiMMveRm9rGUDlpH_eblq3JzmqaQ',
    appId: '1:346129230060:web:56c4cc8c00b5364a75ddc9',
    messagingSenderId: '346129230060',
    projectId: 'nossa-lista-de-compras-c1325',
    databaseURL: 'https://nossa-lista-de-compras-c1325-default-rtdb.firebaseio.com',
    authDomain: 'nossa-lista-de-compras-c1325.firebaseapp.com',
    storageBucket: 'nossa-lista-de-compras-c1325.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnVcLNWoQ7VwCrtbLFltsO5Z5QsuM1hI',
    appId: '1:346129230060:android:edf5809d6a142dea75ddc9',
    messagingSenderId: '346129230060',
    databaseURL: 'https://nossa-lista-de-compras-c1325-default-rtdb.firebaseio.com',
    projectId: 'nossa-lista-de-compras-c1325',
    storageBucket: 'nossa-lista-de-compras-c1325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRoFwuehvM4npE2ps-QXH3q40NvgFvkio',
    appId: '1:346129230060:ios:a7f8582b18bcf43e75ddc9',
    messagingSenderId: '346129230060',
    projectId: 'nossa-lista-de-compras-c1325',
    storageBucket: 'nossa-lista-de-compras-c1325.appspot.com',
    iosClientId: '346129230060-5gq5dtfulejn8nosko77cq2qnhjql2ta.apps.googleusercontent.com',
    iosBundleId: 'com.ufop.nossaListaDeCompras',
  );
}
